CC = gcc -m64 -g

all: int overflow float

int: int.c
	$(CC) int.c -o int

overflow: overflow.c
	$(CC) overflow.c -o overflow

float: float.c
	$(CC) float.c -o float

clean: 
	rm -f int overflow float


